const countries = {
    "ar-SA": "Arabic",
    "zh-CN": "Chinese (Simplified)",
    "hr-HR": "Croatian",
    "cs-CZ": "Czech",
    "da-DK": "Danish",
    "nl-NL": "Dutch",
    "fi-FI": "Finnish",
    "fr-FR": "French",
    "de-DE": "German",
    "el-GR": "Greek",
    "he-IL": "Hebrew",
    "hu-HU": "Hungarian",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "ko-KR": "Korean",
    "no-NO": "Norwegian",
    "pl-PL": "Polish",
    "pt-PT": "Portuguese",
    "ru-RU": "Russian",
    "es-ES": "Spanish",
    "sv-SE": "Swedish",
    "tr-TR": "Turkish",
    "uk-UA": "Ukrainian"
};